### ISSUE TITLE
Zodios has issues with older typescript versions

### ISSUE THREAD

**Issue by ecyrbe** [ecyrbe/zodios#156]
So it seems that zodios has issues with typescript v4.5.4.  
  
Identify which version of typescript zodios is compatible with and make this a peer dependency.

**Comment by QzCurious** [comment]
I'm identifying the problem by inspecting alias query. The incompatible typescript version would fail to infer the alias query hook. 
![image](https://user-images.githubusercontent.com/38932402/192546745-03ade058-cb2a-4897-b865-fb534b454448.png)


The very first version that works find is v4.7.0-beta. Targeting on typescript@4.7.2 might be a good choice, as other v4.7 before it seem like unstable versions (postpending some notion after version tag).
![image](https://user-images.githubusercontent.com/38932402/192547074-1c49f834-502e-4a36-a8cc-f72329bdb55a.png)

In addition, note the comments on my screenshots. The problem only occured on `@zodios/react`.

**Comment by ecyrbe** [comment]
Thank you, i'll check first if i can fixe this issue, as it seems to be only on query. I might have an Idea where this is coming from.

**Comment by ecyrbe** [comment]
Can you upgrade to v9.4 of '@zodios/react' if the issue  is still there for you?

**Comment by ecyrbe** [comment]
ok, i identified the issue. I was using a feature only available in ts 4.7.
`@zodios/react` should now work again in v9.4.1 starting from ts 4.5 (should work with earlier versions also, but ts 4.5 tail recursion optimisation will limit the size of the declared api, so i'll advertise ts 4.5 only support.
